apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cloudbeaver-certificate
  namespace: istio-system
  labels:
    app-name: CloudBeaver
    version: ${CLOUDBEAVER_VERSION}
    component: database-client
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$CLOUDBEAVER_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: cloudbeaver-letsencrypt-certificate