kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloudbeaver-config-pvc
  finalizers: []
  namespace: mysql
  labels:
    app-name: CloudBeaver
    version: ${CLOUDBEAVER_VERSION}
    component: database-client
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-class
  resources:
    requests:
      storage: 5Gi
  volumeName: "cloudbeaver-config-pv"