apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: adguard-certificate
  namespace: istio-system
  labels:
    app-name: adguard
    version: "${ADGUARD_VERSION}"
    component: dns-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$ADGUARD_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: adguard-letsencrypt-certificate