datadog:
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
clusterAgent:
  enabled: true
  resources: 
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi
  confd:
    mysql.yaml: |-
      cluster_check: true
      instances:
        - server: 'mysql-svc.mysql'
          port: 3306
          user: datadog
          pass: '${DATADOG_MYSQL_PASSWORD}'
    istio.yaml: |-
      init_config:
      instances:
        - istiod_endpoint: http://istiod.istio-system:15014/metrics
    envoy.yaml: |-
      init_config:
      instances:
        - stats_url: http://localhost:80/stats
    