apiVersion: v1
kind: Secret
metadata:
  name: samba-secret
  namespace: timemachine
  labels:
    app-name: timemachine
    version: "${AVAHI_VERSION}"
    component: samba-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  SAMBA_USER_NAME: ${USERNAME}
  SAMBA_PASS: ${PASSWORD}