apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avahi-config-pvc
  namespace: timemachine
  labels:
    app-name: timemachine
    version: "${AVAHI_VERSION}"
    component: avahi-discovery-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-data-pvc
  namespace: timemachine
  labels:
    app-name: timemachine
    version: "${AVAHI_VERSION}"
    component: samba-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Gi"