apiVersion: v1
kind: Secret
metadata:
  name: plex-secret
  namespace: plex
  labels:
    app-name: plex
    version: ${PLEX_VERSION}
    component: media-server
    hostNetwork: "yes"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  claim-ref: ${PLEX_CLAIM_REF} #https://www.plex.tv/claim/