apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
  labels:
    app-name: plex
    version: ${PLEX_VERSION}
    component: media-server
    hostNetwork: "yes"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
  - "ReadWriteOnce"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
  namespace: plex
  labels:
    app-name: plex
    version: ${PLEX_VERSION}
    component: media-server
    hostNetwork: "yes"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
  - "ReadWriteOnce"