apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: plex-certificate
  namespace: plex
  labels:
    app-name: plex
    version: ${PLEX_VERSION}
    component: media-server
    hostNetwork: "yes"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$PLEX_DOMAIN'
  issuerRef:
    kind: Issuer
    name: letsencrypt
    namespace: cert-manager
  secretName: plex-letsencrypt-certificate