apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: blog
  labels:
    app-name: wordpress
    version: ${WORDPRESS_VERSION}
    component: blog-servre
    hostNetwork: "no"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"