apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wordpress-certificate
  namespace: istio-system
  labels:
    app-name: wordpress
    version: ${WORDPRESS_VERSION}
    component: blog-servre
    hostNetwork: "no"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$WORDPRESS_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wordpress-letsencrypt-certificate