apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: focalboard-certificate
  namespace: istio-system
  labels:
    app-name: focalboard
    version: "${FOCALBOARD_VERSION}"
    component: project-management-tool
    hostNetwork: "no"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$FOCALBOARD_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: focalboard-letsencrypt-certificate