apiVersion: v1
kind: ConfigMap
metadata:
  name: focalboard-config
  namespace: pm
  labels:
    app-name: focalboard
    version: "${FOCALBOARD_VERSION}"
    component: project-management-tool
    hostNetwork: "no"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
data:
  config.json: |-
    {
        "serverRoot": "http://localhost:8000",
        "port": 8000,
        "dbtype": "postgres",
        "dbconfig": "postgres://focalboarduser:${FOCALBOARD_PASSWORD}@focalboard/boards?sslmode=disable&connect_timeout=10",
        "postgres_dbconfig": "dbname=boards sslmode=disable",
        "useSSL": false,
        "webpath": "./pack",
        "filespath": "./files",
        "telemetry": true,
        "prometheus_address": ":9092",
        "session_expire_time": 2592000,
        "session_refresh_time": 18000,
        "localOnly": false,
        "enableLocalMode": true,
        "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
    }