kind: Namespace
apiVersion: v1
metadata:
  name: mysql
  labels:
    app-name: mysql
    version: ${MYSQL_VERSION}
    component: database-server
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten