apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    app-name: mysql
    version: ${MYSQL_VERSION}
    component: database-server
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  mysql-root-password: "${ROOT_PASSWORD}"