apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app-name: mysql
    version: ${MYSQL_VERSION}
    component: database-server
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: tcp
  selector:
    app-name: mysql
