apiVersion: v1
kind: Secret
metadata:
  name: transmission-secret
  namespace: transmission
  labels:
    app-name: transmission
    version: "${TRANSMISSION_VERSION}"
    component: torrent-download-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  transmission-username: "${TRANSMISSION_USER_NAME}"
  transmission-password: "${TRANSMISSION_PASSWORD}"