apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  finalizers: null
  namespace: transmission
  labels:
    app-name: transmission
    version: "${TRANSMISSION_VERSION}"
    component: torrent-download-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  claimRef:
    name: transmission-config-pvc
    namespace: transmission
  local:
    path: ${TRANSMISSION_CONF_DIR}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - $NODE_NAME
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data-pv
  finalizers: null
  namespace: transmission
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  claimRef:
    name: transmission-data-pvc
    namespace: transmission
  local:
    path: ${TRANSMISSION_DATA_DIR}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - $NODE_NAME