apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
  labels:
    app-name: keycloak
    version: "${KEYCLOAK_VERSION}"
    component: sso-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  keycloak-db-password: "${KEYCLOAK_DB_PASSWORD}"
  keycloak-password: "${KEYCLOAK_PASSWORD}"