apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: keycloak-certificate
  namespace: istio-system
  labels:
    app-name: keycloak
    version: "${KEYCLOAK_VERSION}"
    component: sso-server
    hostNetwork: "no"
    internal-service: "no"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$KEYCLOAK_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: keycloak-letsencrypt-certificate