apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiooperator
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 501m
              memory: 512Mi
            requests:
              cpu: 101m
              memory: 128Mi
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 502m
              memory: 512Mi
            requests:
              cpu: 102m
              memory: 128Mi
  values:
    global:
      defaultResources:
        requests:
          cpu: 10m
          memory: 12Mi
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      proxy:
        resources:
          limits:
            cpu: 503m
            memory: 512Mi
          requests:
            cpu: 103m
            memory: 128Mi
      proxy_init:
        resources:
          limits:
            cpu: 504m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 10Mi