apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app-name: "postgres"
    version: "${POSTGRES_VERSION}"
    component: "database-server"
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: "chynten"
    created-by: "chynten"
type: Opaque
data:
  postgres-root-password: "${POSTGRES_PASSWORD}"