kind: Namespace
apiVersion: v1
metadata:
  name: postgres
  labels:
    app-name: postgres
    version: ${POSTGRES_VERSION}
    component: database-server
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten