apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config-pvc
  namespace: plex
  labels:
    app-name: tautulli
    version: "${TAUTULLI_VERSION}"
    component: plex-analysis-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"