apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tautulli-certificate
  namespace: istio-system
  labels:
    app-name: tautulli
    version: "${TAUTULLI_VERSION}"
    component: plex-analysis-server
    hostNetwork: "yes"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$TAUTULLI_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tautulli-letsencrypt-certificate