apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  acme:
    email: chintanpatel.it@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "DST Root CA X3"
    privateKeySecretRef:
      name: chynten-com-account-key
    solvers:
      - dns01:
          cloudflare:
            email: ${CLOUDFLARE_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token