apiVersion: v1
kind: Secret
metadata:
  name: huginn-secret
  namespace: agent
  labels:
    app-name: huginn
    version: ${HUGINN_VERSION}
    component: agent-to-handover-work
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
type: Opaque
data:
  huginn-db-password: "${HUGINN_DB_PASSWORD}"
  gmail-email: "${GMAIL_EMAIL}"
  gmail-smtp-password: "${GMAIL_SMTP_PASSWORD}"
