apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cloudbeaver-certificate
  namespace: istio-system
  labels:
    app-name: huginn
    version: ${HUGINN_VERSION}
    component: agent-to-handover-work
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  dnsNames:
    - '$HUGINN_DOMAIN'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: huginn-letsencrypt-certificate