kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: huginn-data-pvc
  finalizers: []
  namespace: huginn
  labels:
    app-name: huginn
    version: ${HUGINN_VERSION}
    component: agent-to-handover-work
    hostNetwork: "no"
    internal-service: "yes"
    managed-by: chynten
    created-by: chynten
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-class
  resources:
    requests:
      storage: 5Gi
  volumeName: "huginn-data-pv"